---
- name: Install NCPA and Register Host and Services
  hosts: all
  remote_user: vagrant 
  become: true
  become_method: sudo

  vars_files:
    - 'secrets.yml'
  vars:
    xi_ip: '192.168.1.177'

  roles:
    - role: ncpa_install_linux
    - role: register_with_xi
    - role: xi_apply_config
